# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(601, 395)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_window = QtWidgets.QFrame(Dialog)
        self.frame_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_window.setObjectName("frame_window")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_window)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_node = QtWidgets.QFrame(self.frame_window)
        self.frame_node.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_node.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_node.setObjectName("frame_node")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_node)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_nodeName = QtWidgets.QLineEdit(self.frame_node)
        self.lineEdit_nodeName.setAutoFillBackground(False)
        self.lineEdit_nodeName.setInputMask("")
        self.lineEdit_nodeName.setText("")
        self.lineEdit_nodeName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_nodeName.setObjectName("lineEdit_nodeName")
        self.gridLayout_2.addWidget(self.lineEdit_nodeName, 0, 0, 1, 1)
        self.button_create_tree = QtWidgets.QPushButton(self.frame_node)
        self.button_create_tree.setObjectName("button_create_tree")
        self.gridLayout_2.addWidget(self.button_create_tree, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_node, 0, 0, 1, 1)
        self.frame_tree = QtWidgets.QFrame(self.frame_window)
        self.frame_tree.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tree.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tree.setObjectName("frame_tree")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_tree)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3.addWidget(self.frame_tree, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_window, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "PyQt5 Starter App"))
        self.lineEdit_nodeName.setPlaceholderText(_translate("Dialog", "Enter Node Name"))
        self.button_create_tree.setText(_translate("Dialog", "Create Tree"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
